export enum ActionType {
  "LEFT_OPERAND_APPENDED",
  "RIGHT_OPERAND_APPENDED",
  "OPERATOR_SET",
  "WINDOW_CLEARED",
  "ANSWER_CALCULATED",
}

/*
This should be different:

NUMBER_PRESSED
OPERATOR_PRESSED
EQUALS_PRESSED
CLEAR_PRESSED
DECIMAL_PRESSED
PERCENT_PRESSED
PLUS_MINUS_PRESSED
*/
